import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

/// Immutable description of a DBS electrode model.
///
/// Ports the Python `ElectrodeModel` class from
/// `src/dbs_annotator/config_electrode_models.py`. Instances are normally
/// loaded from the generated contract `schema/electrode_models.json` (the
/// desktop app is the source of truth) rather than hard-coded.
class ElectrodeModel {
  const ElectrodeModel({
    required this.name,
    required this.numContacts,
    required this.contactHeight,
    required this.contactSpacing,
    required this.leadDiameter,
    required this.isDirectional,
    required this.tipContact,
    required this.segmentsPerLevel,
    required this.directionalLevels,
    required this.levelDirectional,
  });

  factory ElectrodeModel.fromJson(Map<String, dynamic> json) {
    return ElectrodeModel(
      name: json['name'] as String,
      numContacts: json['num_contacts'] as int,
      contactHeight: (json['contact_height'] as num).toDouble(),
      contactSpacing: (json['contact_spacing'] as num).toDouble(),
      leadDiameter: (json['lead_diameter'] as num).toDouble(),
      isDirectional: json['is_directional'] as bool,
      tipContact: json['tip_contact'] as bool,
      segmentsPerLevel: json['segments_per_level'] as int,
      directionalLevels: (json['directional_levels'] as List?)
          ?.map((e) => e as int)
          .toList(growable: false),
      levelDirectional: (json['level_directional'] as List)
          .map((e) => e as bool)
          .toList(growable: false),
    );
  }

  /// Human-readable model name (also the catalog key in most cases).
  final String name;

  /// Number of contact levels along the lead.
  final int numContacts;

  /// Contact height in mm.
  final double contactHeight;

  /// Spacing between contacts in mm.
  final double contactSpacing;

  /// Lead diameter in mm.
  final double leadDiameter;

  /// Whether the lead has directional (segmented) levels.
  final bool isDirectional;

  /// True if the distal contact IS the tip (e.g. Boston Scientific).
  final bool tipContact;

  /// 3 for directional leads, 1 otherwise.
  final int segmentsPerLevel;

  /// Optional 0-indexed list of levels that are segmented. `null` means the
  /// Python default applies (all levels except the first and last); the
  /// resolved per-level answer is always available in [levelDirectional].
  final List<int>? directionalLevels;

  /// Pre-computed per-level directionality (length == [numContacts]),
  /// generated by the schema exporter from the Python
  /// `is_level_directional()` logic.
  final List<bool> levelDirectional;

  /// Whether the given level index has directional (segmented) contacts.
  bool isLevelDirectional(int levelIdx) => levelDirectional[levelIdx];
}

/// The full electrode catalog: models keyed by name, plus manufacturer
/// grouping for the UI. Mirrors `ELECTRODE_MODELS` and `MANUFACTURERS` in
/// the Python config module.
class ElectrodeCatalog {
  const ElectrodeCatalog({required this.models, required this.manufacturers});

  /// Parses the structure of `schema/electrode_models.json`:
  /// `{manufacturers: {mfr: [names]}, models: {name: {...}}}`.
  factory ElectrodeCatalog.fromJson(Map<String, dynamic> json) {
    final modelsJson = json['models'] as Map<String, dynamic>;
    final models = <String, ElectrodeModel>{
      for (final entry in modelsJson.entries)
        entry.key:
            ElectrodeModel.fromJson(entry.value as Map<String, dynamic>),
    };

    final manufacturersJson = json['manufacturers'] as Map<String, dynamic>;
    final manufacturers = <String, List<String>>{
      for (final entry in manufacturersJson.entries)
        entry.key: (entry.value as List)
            .map((e) => e as String)
            .toList(growable: false),
    };

    return ElectrodeCatalog(models: models, manufacturers: manufacturers);
  }

  /// Electrode models keyed by catalog name.
  final Map<String, ElectrodeModel> models;

  /// Manufacturer name -> ordered list of model names.
  final Map<String, List<String>> manufacturers;
}

/// Loads the electrode catalog from the bundled asset at runtime.
///
/// NOTE: the build/CI copies the repo-root `schema/*.json` contracts into
/// `app/assets/schema/` before building, so the bundled file is always the
/// generated one (source of truth: the Python desktop app). Tests read the
/// repo-root file directly via `dart:io` instead.
Future<ElectrodeCatalog> loadElectrodeCatalog() async {
  final raw =
      await rootBundle.loadString('assets/schema/electrode_models.json');
  return ElectrodeCatalog.fromJson(jsonDecode(raw) as Map<String, dynamic>);
}
