"""Generate the session-report example TSV table for Sphinx docs.

Reads the committed example programming-session file under
``docs/_static/session_report_example/`` and writes a list-table include for
``docs/output_format.rst``.
"""

from __future__ import annotations

import csv
from pathlib import Path

EXAMPLE_DIR = Path("docs/_static/session_report_example")
OUTPUT_FILE = Path("docs/_generated/session_report_example_tsv.inc.rst")

DISPLAY_COLUMNS: tuple[tuple[str, str], ...] = (
    ("block_ID", "Block"),
    ("is_initial", "Initial"),
    ("scale_name", "Scale"),
    ("scale_value", "Value"),
    ("left_cathode", "L cathode"),
    ("right_cathode", "R cathode"),
    ("right_amplitude", "R amp (mA)"),
    ("notes", "Notes"),
)

NOTES_MAX_LEN = 52


def _example_tsv_path() -> Path:
    files = sorted(EXAMPLE_DIR.glob("sub-*_task-programming_*_events.tsv"))
    if not files:
        raise FileNotFoundError(
            f"No example programming-session TSV found under {EXAMPLE_DIR}/"
        )
    if len(files) > 1:
        names = ", ".join(p.name for p in files)
        raise ValueError(f"Expected one example TSV in {EXAMPLE_DIR}/, found: {names}")
    return files[0]


def _truncate_notes(value: str) -> str:
    text = " ".join(value.split())
    if len(text) <= NOTES_MAX_LEN:
        return text
    return text[: NOTES_MAX_LEN - 1] + "…"


def _cell(value: str, *, column: str) -> str:
    text = _truncate_notes(value) if column == "notes" else value.strip()
    if not text:
        return "—"
    return f"``{text}``"


def build_rst(tsv_path: Path | None = None) -> str:
    path = tsv_path or _example_tsv_path()
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))

    if not rows:
        raise ValueError(f"No data rows in {path}")

    widths = "6 6 14 8 10 12 10 34"
    lines = [
        "..",
        "   Auto-generated by scripts/generate_session_report_example_docs.py.",
        "   Do not edit manually; regenerate from the example TSV file.",
        "",
        ".. list-table::",
        f"   :widths: {widths}",
        "   :header-rows: 1",
        "",
    ]
    header = "   * - " + "\n     - ".join(label for _, label in DISPLAY_COLUMNS)
    lines.append(header)

    for row in rows:
        cells = [_cell(row.get(key, ""), column=key) for key, _ in DISPLAY_COLUMNS]
        lines.append("   * - " + "\n     - ".join(cells))

    lines.append("")
    return "\n".join(lines)


def main(*, check: bool = False) -> int:
    rendered = build_rst()
    if check:
        if not OUTPUT_FILE.exists():
            print(f"[session-report-docs] Missing generated file: {OUTPUT_FILE}")
            return 1
        existing = OUTPUT_FILE.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                "[session-report-docs] Session report example table is out of date. "
                "Run `uv run python scripts/generate_session_report_example_docs.py`."
            )
            return 1
        print("[session-report-docs] Session report example table is up to date.")
        return 0

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(rendered, encoding="utf-8")
    print(f"[session-report-docs] Wrote {OUTPUT_FILE}")
    return 0


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the generated file is missing or out of date.",
    )
    raise SystemExit(main(check=parser.parse_args().check))
