"""Generate InnoSetup script with current version from __init__.py."""

import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
SRC_DIR = PROJECT_ROOT / "src"
INIT_PATH = SRC_DIR / "dbs_annotator" / "__init__.py"


def read_version() -> str:
    """Read version from __init__.py."""
    text = INIT_PATH.read_text(encoding="utf-8")
    m = re.search(
        r'^__version__\s*=\s*["\']([^"\']+)["\']\s*$', text, flags=re.MULTILINE
    )
    if not m:
        raise RuntimeError(f"Could not determine version from {INIT_PATH}")
    return m.group(1)


def generate_iss(version: str) -> None:
    """Generate ClinicalDBSAnnotator.iss with current version."""
    version_underscore = version.replace(".", "_")
    # Use $V$ and $VU$ as placeholders to avoid any conflict with InnoSetup braces
    iss_content = """\
; Inno Setup installer script for ClinicalDBSAnnotator
; Requires Inno Setup 6.x or later to compile
; Auto-generated by generate_iss.py - DO NOT EDIT MANUALLY

#define AppName "ClinicalDBSAnnotator"
#define AppVersion "$V$"
#define AppPublisher "Brain Modulation Lab"
#define AppURL "https://github.com/bml/dbs-annotator"
#define AppExeName "ClinicalDBSAnnotator_Windows_$VU$.exe"

[Setup]
AppId={{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}
DefaultDirName={autopf}\\{#AppName}
DefaultGroupName={#AppName}
AllowNoIcons=yes
OutputDir=installer_output
OutputBaseFilename={#AppName}_Setup_{#AppVersion}_Windows
Compression=lzma2/max
SolidCompression=yes
WizardStyle=Modern
SetupIconFile=..\\icons\\logoneutral.ico
UninstallDisplayIcon={app}\\{#AppExeName}
ChangesAssociations=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "italian"; MessagesFile: "compiler:Languages\\Italian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; OnlyBelowVersion: 6.1

[Files]
; Main application files from PyInstaller onedir build
Source: "dist\\ClinicalDBSAnnotator_Windows_$VU$\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Icon file for shortcuts
Source: "..\\icons\\logoneutral.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\\{#AppName}"; Filename: "{app}\\{#AppExeName}"; IconFilename: "{app}\\logoneutral.ico"
Name: "{commondesktop}\\{#AppName}"; Filename: "{app}\\{#AppExeName}"; IconFilename: "{app}\\logoneutral.ico"; Tasks: desktopicon
Name: "{userappdata}\\Microsoft\\Internet Explorer\\Quick Launch\\{#AppName}"; Filename: "{app}\\{#AppExeName}"; IconFilename: "{app}\\logoneutral.ico"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\\{#AppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(AppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
; File association for .tsv annotation files
Root: HKCR; Subkey: ".tsv\\OpenWithProgids"; ValueType: string; ValueName: "ClinicalDBSAnnotator.tsv"; ValueData: ""; Flags: uninsdeletevalue
Root: HKCR; Subkey: "ClinicalDBSAnnotator.tsv"; ValueType: string; ValueName: ""; ValueData: "Clinical DBS Annotator File"; Flags: uninsdeletekey
Root: HKCR; Subkey: "ClinicalDBSAnnotator.tsv\\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\\logoneutral.ico,0"
Root: HKCR; Subkey: "ClinicalDBSAnnotator.tsv\\shell\\open\\command"; ValueType: string; ValueName: ""; ValueData: "$DQ${app}\\{#AppExeName}$DQ$ $DQ$%1$DQ$"

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
"""
    iss_content = (
        iss_content.replace("$V$", version)
        .replace("$VU$", version_underscore)
        .replace("$DQ$", '"')
    )
    iss_path = PROJECT_ROOT / "scripts" / "ClinicalDBSAnnotator.iss"
    iss_path.write_text(iss_content, encoding="utf-8")
    print(f"Generated {iss_path} with version {version}")


if __name__ == "__main__":
    version = read_version()
    generate_iss(version)
