"""Generate the session-report example TSV table for Sphinx docs.

Reads the committed example programming-session file under
``docs/_static/session_report_example/`` and writes a copyable ``code-block``
include for the *Example rows* section in ``docs/output_format.rst``.
"""

from __future__ import annotations

import csv
from pathlib import Path

EXAMPLE_DIR = Path("docs/_static/session_report_example")
OUTPUT_FILE = Path("docs/_generated/session_report_example_tsv.inc.rst")

# Non-stimulation columns shown in the abbreviated doc preview.
DISPLAY_COLUMNS: tuple[tuple[str, str], ...] = (
    ("date", "date"),
    ("time", "time"),
    ("timezone", "timezone"),
    ("block_ID", "block_ID"),
    ("session_ID", "session_ID"),
    ("is_initial", "is_initial"),
    ("scale_name", "scale_name"),
    ("scale_value", "scale_value"),
    ("program_ID", "program_ID"),
    ("electrode_model", "electrode_model"),
    ("notes", "notes"),
)

# Repeated on the first row of each block only (omitted on continuation lines).
BLOCK_METADATA_KEYS = frozenset(
    {"date", "time", "timezone", "program_ID", "electrode_model", "notes"}
)

ELECTRODE_MODEL_MAX_LEN = 20
NOTES_MAX_LEN = 36


def _example_tsv_path() -> Path:
    files = sorted(EXAMPLE_DIR.glob("sub-*_task-programming_*_events.tsv"))
    if not files:
        raise FileNotFoundError(
            f"No example programming-session TSV found under {EXAMPLE_DIR}/"
        )
    if len(files) > 1:
        names = ", ".join(p.name for p in files)
        raise ValueError(f"Expected one example TSV in {EXAMPLE_DIR}/, found: {names}")
    return files[0]


def _truncate_electrode_model(value: str) -> str:
    text = value.strip()
    if len(text) <= ELECTRODE_MODEL_MAX_LEN:
        return text
    return text[: ELECTRODE_MODEL_MAX_LEN - 1] + "…"


def _truncate_notes(value: str) -> str:
    text = " ".join(value.split())
    if len(text) <= NOTES_MAX_LEN:
        return text
    return text[: NOTES_MAX_LEN - 1] + "…"


def _display_value(row: dict[str, str], key: str) -> str:
    raw = row.get(key, "").strip()
    if key == "electrode_model":
        return _truncate_electrode_model(raw)
    if key == "notes":
        return _truncate_notes(raw)
    return raw


def _format_table_rows(rows: list[dict[str, str]]) -> list[list[str]]:
    formatted: list[list[str]] = []
    prev_block_id: str | None = None

    for row in rows:
        block_id = row.get("block_ID", "").strip()
        is_continuation = prev_block_id is not None and block_id == prev_block_id
        prev_block_id = block_id

        line: list[str] = []
        for key, _ in DISPLAY_COLUMNS:
            if is_continuation and key in BLOCK_METADATA_KEYS:
                line.append("")
            else:
                line.append(_display_value(row, key))
        formatted.append(line)

    return formatted


def _column_widths(headers: tuple[str, ...], rows: list[list[str]]) -> list[int]:
    widths = [len(header) for header in headers]
    for row in rows:
        for index, cell in enumerate(row):
            widths[index] = max(widths[index], len(cell))
    return widths


def build_rst(tsv_path: Path | None = None) -> str:
    path = tsv_path or _example_tsv_path()
    with path.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))

    if not rows:
        raise ValueError(f"No data rows in {path}")

    headers = tuple(label for _, label in DISPLAY_COLUMNS)
    table_rows = _format_table_rows(rows)
    widths = _column_widths(headers, table_rows)

    header_line = "   " + "  ".join(
        header.ljust(widths[i]) for i, header in enumerate(headers)
    )
    lines = [
        "..",
        "   Auto-generated by scripts/generate_session_report_example_docs.py.",
        "   Do not edit manually; regenerate from the example TSV file.",
        "",
        ".. code-block:: text",
        "",
        header_line.rstrip(),
    ]

    for row in table_rows:
        cells = [
            cell.ljust(widths[i]) if cell else " " * widths[i]
            for i, cell in enumerate(row)
        ]
        lines.append(("   " + "  ".join(cells)).rstrip())

    lines.append("")
    return "\n".join(lines)


def main(*, check: bool = False) -> int:
    rendered = build_rst()
    if check:
        if not OUTPUT_FILE.exists():
            print(f"[session-report-docs] Missing generated file: {OUTPUT_FILE}")
            return 1
        existing = OUTPUT_FILE.read_text(encoding="utf-8")
        if existing != rendered:
            print(
                "[session-report-docs] Session report example table is out of date. "
                "Run `uv run python scripts/generate_session_report_example_docs.py`."
            )
            return 1
        print("[session-report-docs] Session report example table is up to date.")
        return 0

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(rendered, encoding="utf-8")
    print(f"[session-report-docs] Wrote {OUTPUT_FILE}")
    return 0


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the generated file is missing or out of date.",
    )
    raise SystemExit(main(check=parser.parse_args().check))
